version: '3.8'
name: se-app

services:
  app:
    image: cosmtrek/air:latest
    restart: always
    container_name: app
    working_dir: /app
    environment:
      - GOPROXY=https://goproxy.io,direct
    volumes:
      - .:/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    networks:
      - postgres-network

  postgres:
    container_name: my_postgres
    restart: on-failure
    image: ${DOCKER_REGISTRY:-docker.io}/postgres:16.1-alpine3.19
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=local
    profiles:
      - postgres

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
