apiVersion: apps/v1
kind: Deployment
metadata:
  name: mass-media-core-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mass-media-core
  template:
    metadata:
      labels:
        app: mass-media-core
    spec:
      containers:
        - name: mass-media-core
          image: your-docker-image:latest
          ports:
            - containerPort: 1234
          env:
            - name: SERVER_PORT
              value: "1234"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
