definitions:
  dto.TrainerProfileCard:
    properties:
      coach_experience:
        type: integer
      contact:
        type: string
      country:
        type: string
      email:
        type: string
      language:
        type: string
      role:
        type: string
      status:
        type: string
      user_name:
        type: string
    type: object
  dto.TrainerResponse:
    properties:
      achievements:
        type: string
      education:
        type: string
      sports:
        type: string
      trainer_profile_card:
        $ref: '#/definitions/dto.TrainerProfileCard'
    type: object
  dto.User:
    properties:
      block:
        type: boolean
      email:
        type: string
      first_name:
        type: string
      info_id:
        type: string
      info_type:
        type: string
      last_name:
        type: string
      password:
        minLength: 8
        type: string
      phone_number:
        minLength: 11
        type: string
      type:
        type: string
      wallet:
        type: integer
    required:
    - email
    - first_name
    - last_name
    - password
    - phone_number
    - type
    type: object
  dto.UserResponse:
    properties:
      block:
        type: boolean
      email:
        type: string
      first_name:
        type: string
      info_id:
        type: string
      info_type:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      type:
        type: string
      wallet:
        type: integer
    type: object
info:
  contact: {}
paths:
  /trainer/profile/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves the profile information of a trainer by ID
      parameters:
      - description: Trainer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Trainer profile information
          schema:
            $ref: '#/definitions/dto.TrainerResponse'
        "404":
          description: Trainer not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get trainer profile
      tags:
      - trainer
  /user/login:
    get:
      consumes:
      - application/json
      description: Logs in a user using email and password
      parameters:
      - description: Email
        in: body
        name: request
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: request
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: User information
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Invalid request payload
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Log in user
      tags:
      - user
  /user/sign-up:
    post:
      consumes:
      - application/json
      description: Signs up a new user with provided details
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.User'
      produces:
      - application/json
      responses:
        "200":
          description: User information
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Invalid request payload
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Sign up user
      tags:
      - user
swagger: "2.0"
